### ISSUE TITLE
uiMode in android:configChanges?

### ISSUE THREAD

**Issue by ryaa** [hinddeep/ionicCapacitorDarkMode#6]
It is more of a question...
Why should we remove uiMode from android:configChanges as stated in the plugin README. This seems to cause the app to restart when it is running in the background mode and the user changes ui mode from/to dark. When this param is present the app is not restarted and the ui mode applied as required.

**Comment by hinddeep** [comment]
Have you checked the code? handleOnRestart() and handleOnResue() functions notify the web layer when the ui mode changes. Now if the activity is not restarted the above-mentioned functions won't be invoked. It is true that the UI mode will be applied to the app but the web layer of the ionic app would have no idea about the change (and hence the code that should be invoked upon the change won't be). That's why we need to remove uiMode from android:configChanges
